# Generated by Django 6.0.4 on 2026-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
