# Generated by Django 6.0.4 on 2026-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('smail', models.CharField(max_length=40)),
                ('spassword', models.CharField(max_length=30)),
                ('conpass', models.CharField(max_length=30)),
            ],
        ),
    ]
